// src/codegen/codegen.cpp
#include "codegen.hpp"
#include <iostream>
#include <sstream>
#include <variant>

std::string CodeGenerator::generate(std::unique_ptr<Stmt>& stmt) {
    output << "; Generated by Scalin compiler\n";
    output << "section .data\n";
    for (const auto& data : dataSection) output << data << "\n";
    output << "\nsection .text\nglobal _start\n\n";
    
    // Générer les déclarations de fonctions d'abord
    if (auto* block = dynamic_cast<BlockStmt*>(stmt.get())) {
        for (auto& s : block->statements) {
            if (s && dynamic_cast<FunctionDecl*>(s.get())) {
                s->accept(*this);
            }
        }
    }
    
    // Générer _start avec le code principal
    output << "_start:\n    mov rbp, rsp\n";
    
    // Générer le code principal (tout sauf les fonctions)
    if (auto* block = dynamic_cast<BlockStmt*>(stmt.get())) {
        for (auto& s : block->statements) {
            if (s && !dynamic_cast<FunctionDecl*>(s.get())) {
                s->accept(*this);
            }
        }
    } else {
        stmt->accept(*this);
    }
    
    // Utiliser rax comme exit code (déjà dans rdi si nécessaire)
    output << "    mov rdi, rax\n";  // Le résultat est dans rax, on le copie dans rdi (exit code)
    output << "    mov rax, 60\n";    // syscall: exit
    output << "    syscall\n";
    return output.str();
}

void CodeGenerator::emit(const std::string& instruction) {
    output << "    " << instruction << "\n";
}

void CodeGenerator::emit(const std::string& instruction, const std::string& operand) {
    output << "    " << instruction << ", " << operand << "\n";
}

void CodeGenerator::loadConstant(const std::any& value) {
    if (value.type() == typeid(int64_t)) {
        emit("mov rax", std::to_string(std::any_cast<int64_t>(value)));
    } else if (value.type() == typeid(double)) {
        emit("mov rax", std::to_string(static_cast<int64_t>(std::any_cast<double>(value))));
    } else if (value.type() == typeid(bool)) {
        emit("mov rax", std::any_cast<bool>(value) ? "1" : "0");
    } else if (value.type() == typeid(char)) {
        emit("mov rax", std::to_string(static_cast<int64_t>(std::any_cast<char>(value))));
    } else if (value.type() == typeid(std::string)) {
        std::string str = std::any_cast<std::string>(value);
        std::string label = "STR" + std::to_string(labelCounter++);
        dataSection.push_back(label + ": db '" + str + "', 0");
        emit("mov rax", label);
    }
}

std::string CodeGenerator::newLabel() {
    return "L" + std::to_string(labelCounter++);
}

std::any CodeGenerator::visitLiteralExpr(Expr& expr) {
    auto& literalExpr = dynamic_cast<LiteralExpr&>(expr);
    
    // Extraire le variant du std::any
    std::variant<int64_t, double, bool, char, std::string> var = std::any_cast<std::variant<int64_t, double, bool, char, std::string>>(literalExpr.value);
    
    // Extraire la valeur du variant
    std::visit([this](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, int64_t>) {
            emit("mov rax", std::to_string(arg));
        } else if constexpr (std::is_same_v<T, double>) {
            emit("mov rax", std::to_string(static_cast<int64_t>(arg)));
        } else if constexpr (std::is_same_v<T, bool>) {
            emit("mov rax", arg ? "1" : "0");
        } else if constexpr (std::is_same_v<T, char>) {
            emit("mov rax", std::to_string(static_cast<int64_t>(arg)));
        } else if constexpr (std::is_same_v<T, std::string>) {
            std::string label = "STR" + std::to_string(labelCounter++);
            dataSection.push_back(label + ": db '" + arg + "', 0");
            emit("mov rax", label);
        }
    }, var);
    return nullptr;
}

std::any CodeGenerator::visitBinaryExpr(Expr& expr) {
    auto& e = dynamic_cast<BinaryExpr&>(expr);
    e.left->accept(*this);
    emit("push rax");  // Sauvegarder la valeur de gauche
    
    e.right->accept(*this);
    
    // Récupérer la valeur de gauche dans rbx
    emit("pop rbx");
    
    switch (e.op.type) {
        case TokenType::PLUS: emit("add rax, rbx"); break;
        case TokenType::MINUS: emit("sub rbx, rax"); emit("mov rax, rbx"); break;
        case TokenType::MULT: emit("imul rax, rbx"); break;
        case TokenType::DIV: emit("cqo"); emit("idiv rbx"); break;
        case TokenType::MOD: emit("cqo"); emit("idiv rbx"); emit("mov rax, rdx"); break;
        case TokenType::EQ: emit("cmp rax, rbx"); emit("sete al"); emit("movzx rax, al"); break;
        case TokenType::NEQ: emit("cmp rax, rbx"); emit("setne al"); emit("movzx rax, al"); break;
        case TokenType::LT: emit("cmp rax, rbx"); emit("setl al"); emit("movzx rax, al"); break;
        case TokenType::GT: emit("cmp rax, rbx"); emit("setg al"); emit("movzx rax, al"); break;
        case TokenType::LE: emit("cmp rax, rbx"); emit("setle al"); emit("movzx rax, al"); break;
        case TokenType::GE: emit("cmp rax, rbx"); emit("setge al"); emit("movzx rax, al"); break;
        default: throw std::runtime_error("Opérateur binaire non supporté");
    }
    return nullptr;
}

std::any CodeGenerator::visitUnaryExpr(Expr& expr) {
    auto& e = dynamic_cast<UnaryExpr&>(expr);
    e.right->accept(*this);
    switch (e.op.type) {
        case TokenType::MINUS: emit("neg rax"); break;
        case TokenType::NOT: emit("test rax, rax"); emit("setz al"); emit("movzx rax, al"); break;
        default: throw std::runtime_error("Opérateur unaire non supporté");
    }
    return nullptr;
}

std::any CodeGenerator::visitVariableExpr(Expr& expr) {
    auto& varExpr = dynamic_cast<VariableExpr&>(expr);
    // Pour l'instant, on suppose que la variable est le premier paramètre (n)
    // Les paramètres sont à [rbp+16], [rbp+24], etc. (car return address est à [rbp+8])
    // On va utiliser [rbp+16] pour le premier paramètre
    if (varExpr.name.lexeme == "n") {
        emit("mov rax, [rbp+16]");
    } else {
        // Variable globale ou non trouvée : retourner 0
        emit("mov rax, 0");
    }
    return nullptr;
}
std::any CodeGenerator::visitGroupingExpr(Expr& expr) { dynamic_cast<GroupingExpr&>(expr).expression->accept(*this); return nullptr; }
std::any CodeGenerator::visitCallExpr(Expr& expr) {
    auto& call = dynamic_cast<CallExpr&>(expr);
    
    // Évaluer les arguments (dans l'ordre inverse pour la pile)
    for (auto it = call.arguments.rbegin(); it != call.arguments.rend(); ++it) {
        (*it)->accept(*this);
        emit("push rax");  // Sauvegarder l'argument sur la pile
    }
    
    // Appeler la fonction
    if (auto* varExpr = dynamic_cast<VariableExpr*>(call.callee.get())) {
        std::string funcLabel = "func_" + varExpr->name.lexeme;
        emit("call " + funcLabel);
    } else {
        throw std::runtime_error("Appel de fonction non supporté: callee n'est pas un identifiant");
    }
    
    // Nettoyer la pile (supprimer les arguments)
    // Note: call push l'adresse de retour, mais elle est poppée par ret
    // Donc on nettoie seulement les arguments
    emit("add rsp", std::to_string(call.arguments.size() * 8));
    
    return nullptr;
}

std::any CodeGenerator::visitIfExpr(Expr& expr) {
    auto& ifExpr = dynamic_cast<IfExpr&>(expr);
    
    // Générer la condition
    ifExpr.condition->accept(*this);
    emit("cmp rax, 0");
    
    // Saut vers else si la condition est fausse
    std::string elseLabel = newLabel();
    std::string endLabel = newLabel();
    emit("je " + elseLabel);
    
    // Générer la branche then
    ifExpr.thenBranch->accept(*this);
    emit("jmp " + endLabel);
    
    // Générer la branche else
    emit(elseLabel + ":");
    if (ifExpr.elseBranch) {
        ifExpr.elseBranch->accept(*this);
    }
    
    // Fin de l'expression if
    emit(endLabel + ":");
    
    return nullptr;
}
std::any CodeGenerator::visitGetExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitSetExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitThisExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitSuperExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitVarDecl(Stmt& stmt) {
    auto& decl = dynamic_cast<VarDecl&>(stmt);
    if (decl.initializer) {
        decl.initializer->accept(*this);
    }
    return nullptr;
}
std::any CodeGenerator::visitFunctionDecl(Stmt& stmt) {
    auto& func = dynamic_cast<FunctionDecl&>(stmt);
    
    // Générer le label de la fonction
    std::string funcLabel = "func_" + func.name.lexeme;
    output << funcLabel << ":\n";
    output << "    push rbp\n";
    output << "    mov rbp, rsp\n";
    
    // Allouer de l'espace pour les paramètres locaux (pour l'instant, on suppose 1 paramètre : n)
    // Les paramètres sont passés sur la pile avant l'appel
    // On les copie dans des emplacements locaux (rbp - 8, rbp - 16, etc.)
    // Pour simplifier, on suppose que le premier paramètre est à [rbp+16] (car return address est à [rbp+8])
    // Mais en réalité, les paramètres sont à [rbp+16], [rbp+24], etc. (car call push return address)
    // On va utiliser [rbp+16] pour le premier paramètre
    
    // Générer le corps de la fonction
    if (auto* exprStmt = dynamic_cast<ExpressionStmt*>(func.body.get())) {
        exprStmt->expression->accept(*this);
    } else {
        func.body->accept(*this);
    }
    
    // Épilogue de la fonction
    output << "    mov rsp, rbp\n";
    output << "    pop rbp\n";
    output << "    ret\n";
    output << "\n";
    
    return nullptr;
}
std::any CodeGenerator::visitClassDecl(Stmt&) { return nullptr; }
std::any CodeGenerator::visitExpressionStmt(Stmt& expr) { dynamic_cast<ExpressionStmt&>(expr).expression->accept(*this); return nullptr; }

std::any CodeGenerator::visitIfStmt(Stmt& stmt) {
    auto& s = dynamic_cast<IfStmt&>(stmt);
    s.condition->accept(*this);
    emit("cmp rax, 0");
    std::string elseLabel = newLabel();
    std::string endLabel = newLabel();
    emit("je " + elseLabel);
    s.thenBranch->accept(*this);
    emit("jmp " + endLabel);
    emit(elseLabel + ":");
    if (s.elseBranch) s.elseBranch->accept(*this);
    emit(endLabel + ":");
    return nullptr;
}

std::any CodeGenerator::visitBlockStmt(Stmt& stmt) {
    auto& block = dynamic_cast<BlockStmt&>(stmt);
    for (auto& s : block.statements) {
        if (s) s->accept(*this);
    }
    return nullptr;
}

std::any CodeGenerator::visitWhileStmt(Stmt& stmt) {
    auto& s = dynamic_cast<WhileStmt&>(stmt);
    std::string startLabel = newLabel();
    std::string endLabel = newLabel();
    emit(startLabel + ":");
    s.condition->accept(*this);
    emit("cmp rax, 0");
    emit("je " + endLabel);
    s.body->accept(*this);
    emit("jmp " + startLabel);
    emit(endLabel + ":");
    return nullptr;
}

std::any CodeGenerator::visitReturnStmt(Stmt& stmt) {
    auto& s = dynamic_cast<ReturnStmt&>(stmt);
    if (s.value) s.value->accept(*this);
    emit("mov rsp, rbp");
    emit("pop rbp");
    emit("ret");
    return nullptr;
}