// src/codegen/codegen.cpp
#include "codegen.hpp"
#include <sstream>

std::string CodeGenerator::generate(std::unique_ptr<Stmt>& stmt) {
    output << "； Generated by Scalin compiler\n";
    output << "section .data\n";
    for (const auto& data : dataSection) output << data << "\n";
    output << "\nsection .text\nglobal _start\n\n_start:\n    mov rbp, rsp\n";
    stmt->accept(*this);
    output << "    mov rax, 60\n    xor rdi, rdi\n    syscall\n";
    return output.str();
}

void CodeGenerator::emit(const std::string& instruction) {
    output << "    " << instruction << "\n";
}

void CodeGenerator::emit(const std::string& instruction, const std::string& operand) {
    output << "    " << instruction << " " << operand << "\n";
}

void CodeGenerator::loadConstant(const std::any& value) {
    if (value.type() == typeid(int64_t)) {
        emit("mov rax", std::to_string(std::any_cast<int64_t>(value)));
    } else if (value.type() == typeid(double)) {
        emit("mov rax", std::to_string(static_cast<int64_t>(std::any_cast<double>(value))));
    } else if (value.type() == typeid(bool)) {
        emit("mov rax", std::any_cast<bool>(value) ? "1" : "0");
    } else if (value.type() == typeid(char)) {
        emit("mov rax", std::to_string(static_cast<int64_t>(std::any_cast<char>(value))));
    } else if (value.type() == typeid(std::string)) {
        std::string str = std::any_cast<std::string>(value);
        std::string label = "STR" + std::to_string(labelCounter++);
        dataSection.push_back(label + ": db '" + str + "', 0");
        emit("mov rax", label);
    }
}

std::string CodeGenerator::newLabel() {
    return "L" + std::to_string(labelCounter++);
}

std::any CodeGenerator::visitLiteralExpr(Expr& expr) {
    loadConstant(dynamic_cast<LiteralExpr&>(expr).value);
    return nullptr;
}

std::any CodeGenerator::visitBinaryExpr(Expr& expr) {
    auto& e = dynamic_cast<BinaryExpr&>(expr);
    e.left->accept(*this);
    emit("push rax");
    e.right->accept(*this);
    emit("pop rbx");
    switch (e.op.type) {
        case TokenType::PLUS: emit("add rax, rbx"); break;
        case TokenType::MINUS: emit("sub rbx, rax"); emit("mov rax, rbx"); break;
        case TokenType::MULT: emit("imul rax, rbx"); break;
        case TokenType::DIV: emit("cqo"); emit("idiv rbx"); break;
        case TokenType::MOD: emit("cqo"); emit("idiv rbx"); emit("mov rax, rdx"); break;
        case TokenType::EQ: emit("cmp rax, rbx"); emit("sete al"); emit("movzx rax, al"); break;
        case TokenType::NEQ: emit("cmp rax, rbx"); emit("setne al"); emit("movzx rax, al"); break;
        case TokenType::LT: emit("cmp rbx, rax"); emit("setl al"); emit("movzx rax, al"); break;
        case TokenType::GT: emit("cmp rbx, rax"); emit("setg al"); emit("movzx rax, al"); break;
        case TokenType::LE: emit("cmp rbx, rax"); emit("setle al"); emit("movzx rax, al"); break;
        case TokenType::GE: emit("cmp rbx, rax"); emit("setge al"); emit("movzx rax, al"); break;
        default: throw std::runtime_error("Opérateur binaire non supporté");
    }
    return nullptr;
}

std::any CodeGenerator::visitUnaryExpr(Expr& expr) {
    auto& e = dynamic_cast<UnaryExpr&>(expr);
    e.right->accept(*this);
    switch (e.op.type) {
        case TokenType::MINUS: emit("neg rax"); break;
        case TokenType::NOT: emit("test rax, rax"); emit("setz al"); emit("movzx rax, al"); break;
        default: throw std::runtime_error("Opérateur unaire non supporté");
    }
    return nullptr;
}

std::any CodeGenerator::visitVariableExpr(Expr&) { emit("mov rax, [rbp-8]"); return nullptr; }
std::any CodeGenerator::visitGroupingExpr(Expr& expr) { dynamic_cast<GroupingExpr&>(expr).expression->accept(*this); return nullptr; }
std::any CodeGenerator::visitCallExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitGetExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitSetExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitThisExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitSuperExpr(Expr&) { return nullptr; }
std::any CodeGenerator::visitVarDecl(Stmt&) { return nullptr; }
std::any CodeGenerator::visitFunctionDecl(Stmt&) { return nullptr; }
std::any CodeGenerator::visitClassDecl(Stmt&) { return nullptr; }
std::any CodeGenerator::visitExpressionStmt(Stmt& expr) { dynamic_cast<ExpressionStmt&>(expr).expression->accept(*this); return nullptr; }

std::any CodeGenerator::visitIfStmt(Stmt& stmt) {
    auto& s = dynamic_cast<IfStmt&>(stmt);
    s.condition->accept(*this);
    emit("cmp rax, 0");
    std::string elseLabel = newLabel();
    std::string endLabel = newLabel();
    emit("je " + elseLabel);
    s.thenBranch->accept(*this);
    emit("jmp " + endLabel);
    emit(elseLabel + ":");
    if (s.elseBranch) s.elseBranch->accept(*this);
    emit(endLabel + ":");
    return nullptr;
}

std::any CodeGenerator::visitBlockStmt(Stmt& stmt) {
    for (auto& s : dynamic_cast<BlockStmt&>(stmt).statements) s->accept(*this);
    return nullptr;
}

std::any CodeGenerator::visitWhileStmt(Stmt& stmt) {
    auto& s = dynamic_cast<WhileStmt&>(stmt);
    std::string startLabel = newLabel();
    std::string endLabel = newLabel();
    emit(startLabel + ":");
    s.condition->accept(*this);
    emit("cmp rax, 0");
    emit("je " + endLabel);
    s.body->accept(*this);
    emit("jmp " + startLabel);
    emit(endLabel + ":");
    return nullptr;
}

std::any CodeGenerator::visitReturnStmt(Stmt& stmt) {
    auto& s = dynamic_cast<ReturnStmt&>(stmt);
    if (s.value) s.value->accept(*this);
    emit("mov rsp, rbp");
    emit("pop rbp");
    emit("ret");
    return nullptr;
}